version: 2.0
defaults: &defaults
  working_directory: ~/code-gov-adapters
  docker:
    - image: circleci/node:10.17.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-node-modules
          command: npm install
      - run:
          name: run-linter
          command: npm run lint
      - run:
          name: run-security-check
          command: npm audit
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p ~/code-gov-adapters/tmp
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ~/code-gov-adapters/tmp/cc-test-reporter
            chmod +x ~/code-gov-adapters/tmp/cc-test-reporter
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/code-gov-adapters
          paths: .
  test:
    <<: *defaults
    environment:
      - NODE_ENV: "testing"
      - CC_TEST_REPORTER_ID: 598d76b93fa264e5a8fedefdfe163608cbda511652d1792552176a6f68d87264
    steps:
      - attach_workspace:
          at: ~/code-gov-adapters
      - run:
          command: ~/code-gov-adapters/tmp/cc-test-reporter before-build
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: run-test
          command: npm test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: 
          name: Run tests
          command: |
            mkdir coverage
            npm test
            ./node_modules/.bin/nyc report --reporter=text-lcov > ./coverage/lcov.info
            ~/code-gov-adapters/tmp/cc-test-reporter after-build -t lcov --exit-code $?
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage
          prefix: coverage
      - persist_to_workspace:
          root: ~/code-gov-adapters
          paths:
            - .
            - tmp/codeclimate.json
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/code-gov-adapters
      - run:
          name: Authenticate with NPM registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/code-gov-integrations/.npmrc
      - deploy:
          name: Publish to NPM registry
          command: npm publish --access public

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v(\d+\.*){3}/
            branches:
              ignore: /.*/
