version: 2.0
defaults: &defaults
  working_directory: ~/code-gov-adapters
  environment:
    - CC_TEST_REPORTER_ID: e1477b41ad84c1828f5d
  docker:
    - image: circleci/node:10.8.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-node-modules
          command: npm install
      - run:
          name: run-linter
          command: npm run lint
      - run:
          name: run-security-check
          command: npm audit
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p ~/code-gov-adapters/tmp
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ~/code-gov-adapters/tmp/cc-test-reporter
            chmod +x ~/code-gov-adapters/tmp/cc-test-reporter
            sudo docker-php-ext-enable xdebug
            ~/code-gov-adapters/tmp/cc-test-reporter before-build
            sudo vendor/bin/phpunit --coverage-clover clover.xml
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/code-gov-adapters
          paths: .
  test:
    <<: *defaults
    environment:
      NODE_ENV: "testing"
    steps:
      - attach_workspace:
          at: ~/code-gov-adapters
      #- run:
      #    command: ./cc-test-reporter before-build
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: run-test
          command: npm test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      #- run: 
      #    name: Run tests
      #    command: |
      #      bundle exec rake
      #      ~/code-gov-adapters/tmp/cc-test-reporter format-coverage -t lcov -o ~/code-gov-adapters/tmp/codeclimate.json ~/code-gov-adapters/tmp/lcov.info
      - run:
          name: upload-test-report
          command: ~/code-gov-adapters/tmp/cc-test-reporter after-build -t lcov --exit-code $?
      #- run:
      #    name: make-test-reporter-executable
      #    command: |
      #      sudo docker-php-ext-enable xdebug
      #    # notify Code Climate of a pending test report using `before-build`
      #      ./cc-test-reporter before-build
      #      sudo vendor/bin/phpunit --coverage-clover clover.xml
      #    # upload test report to Code Climate using `after-build`
      #      ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage
          prefix: coverage
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter upload-coverage -i ~/code-gov-adapters/tmp/codeclimate.total.json
      - persist_to_workspace:
          root: ~/code-gov-adapters
          paths:
            - .
            - tmp/codeclimate.json
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/code-gov-adapters
      - run:
          name: Authenticate with NPM registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/code-gov-integrations/.npmrc
      - deploy:
          name: Publish to NPM registry
          command: npm publish --access public

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v(\d+\.*){3}/
            branches:
              ignore: /.*/
